### ISSUE TITLE
reactors are none [Issue]

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#250]
I noticed that `"reactors":"None"`, it seems only one reaction doesn't return, it returns only it has more than one reaction. for example, it should have like, haha, etc...

please check @neon-ninja

**Comment by fashandatafields** [comment]
https://www.facebook.com/Voix.de.biskra/posts/3855820361202097
It gave me comments but not the reaction
@neon-ninja please check

**Comment by neon-ninja** [comment]
This should fix it https://github.com/kevinzg/facebook-scraper/commit/fb17c1aee511640da9ef988d34337478e66db90d

**Comment by fashandatafields** [comment]
what can be the issue? have any idea? @neon-ninja

**Comment by fashandatafields** [comment]
ok cool, thanks @neon-ninja

**Comment by fashandatafields** [comment]
@neon-ninja the issue still exists
Giving same results of none
```
`{
   "post_id":"3855820361202097",
   "text":"من #رسائلكم\n#khaled",
   "post_text":"من #رسائلكم\n#khaled",
   "shared_text":"",
   "time":datetime.datetime(2021,
   5,
   11,
   0,
   14,
   57),
   "image":"https://scontent-lga3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/184285532_3855820291202104_114856109806233400_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=110474&_nc_ohc=58vEoAlBjygAX9m_UF8&_nc_ht=scontent-lga3-1.xx&tp=14&oh=0e1fde028ecf99a228b72357f7f8e60b&oe=60C143A0",
   "image_lowquality":"https://scontent-lga3-1.xx.fbcdn.net/v/t1.6435-0/cp0/e15/q65/p240x240/184285532_3855820291202104_114856109806233400_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=110474&_nc_ohc=58vEoAlBjygAX9m_UF8&_nc_ht=scontent-lga3-1.xx&tp=3&oh=3f2c0c67e856c6919e25e8da1650cce4&oe=60BFDF35",
   "images":[
      "https://scontent-lga3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/184285532_3855820291202104_114856109806233400_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=110474&_nc_ohc=58vEoAlBjygAX9m_UF8&_nc_ht=scontent-lga3-1.xx&tp=14&oh=0e1fde028ecf99a228b72357f7f8e60b&oe=60C143A0"
   ],
   "images_description":[
      "May be an image of \u200eone or more people and \u200etext that says '\u200eمساء الخير اخي ارجو ان تنشرو دون ذكر اسمي وجدت صورة ووصل استلام ملف تسجيل امتحان باكالوريا باسم طهراوي رميساء واريد ان اوصل لها امانتها باذن الله نشكرك على مراسلتنا نحن نسعى\u200e'\u200e\u200e"
   ],
   "images_lowquality":[
      "https://scontent-lga3-1.xx.fbcdn.net/v/t1.6435-0/cp0/e15/q65/p240x240/184285532_3855820291202104_114856109806233400_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=110474&_nc_ohc=58vEoAlBjygAX9m_UF8&_nc_ht=scontent-lga3-1.xx&tp=3&oh=3f2c0c67e856c6919e25e8da1650cce4&oe=60BFDF35"
   ],
   "images_lowquality_description":[
      "May be an image of \u200eone or more people and \u200etext that says '\u200eمساء الخير اخي ارجو ان تنشرو دون ذكر اسمي وجدت صورة ووصل استلام ملف تسجيل امتحان باكالوريا باسم طهراوي رميساء واريد ان اوصل لها امانتها باذن الله نشكرك على مراسلتنا نحن نسعى\u200e'\u200e\u200e"
   ],
   "video":"None",
   "video_duration_seconds":"None",
   "video_height":"None",
   "video_id":"None",
   "video_quality":"None",
   "video_size_MB":"None",
   "video_thumbnail":"None",
   "video_watches":"None",
   "video_width":"None",
   "likes":7,
   "comments":0,
   "shares":0,
   "post_url":"https://facebook.com/875365599247603/posts/3855820361202097",
   "link":"None",
   "user_id":"875365599247603",
   "username":"Voix de biskra صوت بسكرة",
   "user_url":"https://facebook.com/Voix.de.biskra/?__tn__=C-R",
   "is_live":false,
   "factcheck":"None",
   "shared_post_id":"None",
   "shared_time":"None",
   "shared_user_id":"None",
   "shared_username":"None",
   "shared_post_url":"None",
   "available":true,
   "comments_full":"None",
   "reactors":"None",
   "w3_fb_url":"None"
}`
```
Below Post has 2kinds of reactions. But still reactors are null
```
`{
   "post_id":"3855323311251802",
   "text":"من الصفحة الرسمية لفريق اتحاد بسكرة لكرة القدم\n#فلسطين",
   "post_text":"من الصفحة الرسمية لفريق اتحاد بسكرة لكرة القدم\n#فلسطين",
   "shared_text":"",
   "time":datetime.datetime(2021,
   5,
   10,
   20,
   0,
   51),
   "image":"https://scontent-lga3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/185020517_3855323201251813_2377859802777565733_n.jpg?_nc_cat=103&ccb=1-3&_nc_sid=110474&_nc_ohc=tUKoBsTDY-8AX93ib9G&_nc_ht=scontent-lga3-1.xx&tp=14&oh=f59b1e75a4e04264630b214b793482e1&oe=60BDE953",
   "image_lowquality":"https://scontent-lga3-1.xx.fbcdn.net/v/t1.6435-0/cp0/e15/q65/p320x320/185020517_3855323201251813_2377859802777565733_n.jpg?_nc_cat=103&ccb=1-3&_nc_sid=110474&_nc_ohc=tUKoBsTDY-8AX93ib9G&_nc_ht=scontent-lga3-1.xx&tp=3&oh=9898cf5bd8ebad3c703fdcc8f1d5747b&oe=60C0BF17",
   "images":[
      "https://scontent-lga3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/185020517_3855323201251813_2377859802777565733_n.jpg?_nc_cat=103&ccb=1-3&_nc_sid=110474&_nc_ohc=tUKoBsTDY-8AX93ib9G&_nc_ht=scontent-lga3-1.xx&tp=14&oh=f59b1e75a4e04264630b214b793482e1&oe=60BDE953"
   ],
   "images_description":[
      "May be an image of text"
   ],
   "images_lowquality":[
      "https://scontent-lga3-1.xx.fbcdn.net/v/t1.6435-0/cp0/e15/q65/p320x320/185020517_3855323201251813_2377859802777565733_n.jpg?_nc_cat=103&ccb=1-3&_nc_sid=110474&_nc_ohc=tUKoBsTDY-8AX93ib9G&_nc_ht=scontent-lga3-1.xx&tp=3&oh=9898cf5bd8ebad3c703fdcc8f1d5747b&oe=60C0BF17"
   ],
   "images_lowquality_description":[
      "May be an image of text"
   ],
   "video":"None",
   "video_duration_seconds":"None",
   "video_height":"None",
   "video_id":"None",
   "video_quality":"None",
   "video_size_MB":"None",
   "video_thumbnail":"None",
   "video_watches":"None",
   "video_width":"None",
   "likes":5,
   "comments":0,
   "shares":0,
   "post_url":"https://facebook.com/875365599247603/posts/3855323311251802",
   "link":"None",
   "user_id":"875365599247603",
   "username":"Voix de biskra صوت بسكرة",
   "user_url":"https://facebook.com/Voix.de.biskra/?__tn__=C-R",
   "is_live":false,
   "factcheck":"None",
   "shared_post_id":"None",
   "shared_time":"None",
   "shared_user_id":"None",
   "shared_username":"None",
   "shared_post_url":"None",
   "available":true,
   "comments_full":"None",
   "reactors":"None",
   "w3_fb_url":"None"
}`
```

**Comment by fashandatafields** [comment]
earlier it worked without cookies. reactors are visible in facebook-scraper

**Comment by neon-ninja** [comment]
Reactors are visible without cookies for big pages like Nintendo, but not for smaller pages like Voix.de.biskra

**Comment by neon-ninja** [comment]
Reactions/reactors might be visible without cookies for larger pages like Nintendo, but not smaller pages like this one. Even then, it's very easy to trigger an IP ban to stop you reading too many reaction counts anonymously. Best to pass cookies for this task.

```python
posts = get_posts(
    "Nintendo",
    options = {"reactors": True}
)
for post in posts:
    print(post.get("post_id"), post.get("reactions"), post.get("reactors"))
```

```python
4112996902118065 {'like': 714, 'love': 198, 'support': 12, 'anger': 1} None
4106669112750844 {'like': 473, 'love': 87, 'wow': 9, 'haha': 7, 'support': 7, 'anger': 7} None
4088623351222087 {'like': 490, 'love': 77, 'support': 4, 'anger': 4, 'wow': 3} None
4085738151510607 None None
4085430424874713 None None
4079635875454168 None None
4064916226926133 None None
4063920557025700 None None
4061286243955798 None None
4054943884590034 None None
4044341405650282 None None
```

**Comment by fashandatafields** [comment]
@neon-ninja thanks for the information
