### ISSUE TITLE
Content not found error

### ISSUE THREAD

**Issue by cmhc2021** [kevinzg/facebook-scraper#564]
When scraping user posts by user ID, sometimes the program will return "Content Not Found" error.
For example, if I scraped fung.ting.921, when the post goes to 224766614218279, 222425014452439, etc., it will return Content Not Found? Why is that?

**Comment by neon-ninja** [comment]
Try go to https://m.facebook.com/224766614218279 or https://m.facebook.com/222425014452439 in your browser, you can see the Content Not Found error yourself. Maybe these posts were deleted or otherwise suppressed?

**Comment by cmhc2021** [comment]
Does it mean I cannot scrape the comments if the post content is not found?
Because I can see the comment "already read it, it takes me 13mins to read this...orz", but I cannot scrape it because the original post content is not found.

**Comment by neon-ninja** [comment]
Actually, it does seem possible to see 224766614218279 if you have the right link: https://m.facebook.com/story.php?story_fbid=224766614218279&id=100000548265571
Similarly for 222425014452439, https://m.facebook.com/story.php?story_fbid=222425014452439&id=100000548265571. Neither of these posts seem to have comments. They're not really real posts, just likes of other pages.

**Comment by cmhc2021** [comment]
How about 218666674828273?  It has two comments indeed, I'm not sure if I'm able to scrape them.

**Comment by neon-ninja** [comment]
You can if you access it via https://m.facebook.com/story.php?story_fbid=218666674828273&id=100000548265571

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/73e7fd13c04f3c22c17de0a399d0b3b1b564c519 should fix this. This is somewhat the inverse of https://github.com/kevinzg/facebook-scraper/commit/6aa5957c643e08690906c7268015a216e4bdfa0b, which I did for you to fix https://github.com/kevinzg/facebook-scraper/issues/313

**Comment by cmhc2021** [comment]
Thanks.  Sorry I may have made contradictory requests.  I decide to stay with 6aa5957 because some posts which really have no comments will not be missing.  Anyway, I think this content not found problem only happens for very old posts, say, before 2012, and I think I need to accept it as limitation instead.

**Comment by neon-ninja** [comment]
Ah, I might not have made that as clear as it could be - it's not entirely the inverse, it only attempts the behavior prior to https://github.com/kevinzg/facebook-scraper/commit/6aa5957c643e08690906c7268015a216e4bdfa0b in the event of a NotFound exception. Take a closer look at https://github.com/kevinzg/facebook-scraper/commit/73e7fd13c04f3c22c17de0a399d0b3b1b564c519 - the scraper will attempt fetching by post_id (so video post comment extraction works), then if it catches a NotFound exception, fall back to the post_url (so like posts like this work). So, both cases should be covered by https://github.com/kevinzg/facebook-scraper/commit/73e7fd13c04f3c22c17de0a399d0b3b1b564c519

**Comment by cmhc2021** [comment]
oh, yes.  I made a mistake in my last testing.  On testing again, 73e7fd1 should cover 6aa5957 and solve the aforementioned problem.

**Comment by HakzA** [comment]
It seems like the problem still persists, e.g I get `facebook_scraper.exceptions.NotFound: Content Not Found` from trying to get posts from the page "OddsetDK":

`                for post in get_posts(account='OddsetDK', pages=pages, start_url=start_url, request_url_callback=handle_pagination_url):
                    print('Currrent post: ', post)`

**Comment by HakzA** [comment]
It's strange, because when I run in debugger I can see that the start_url is 'https://m.facebook.com/OddsetDK/posts/', which I can acces manually and see posts from. But when I run it through request_fn(start_url), I get the above error message.

**Comment by HakzA** [comment]
Nevermind, the reason I could open it manually was because I was logged in through my browser. However, if you try to open the page in incognito it rightly shows "Content Not Found". If I pass my cookies when getting the post, then I can get the content. Strange how some pages require login while others don't, wonder what determines that.

**Comment by neon-ninja** [comment]
It seems to be correlated with page popularity - the more popular the page, the less likely it is you need to login

**Comment by leungfukwong** [comment]
I encountered "error of content not found" when I tried to scrape ChinaGlobalTVNetwork neither of these codes "get_posts(group='ChinaGlobalTVNetwork'" and "group='100044504436603'  work.  I have email and password credentials specified. Pls help!

**Comment by leungfukwong** [comment]
I also tried to use post_urls... does work either 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/39502448/203698604-c8bef828-c4c4-4642-8a4f-c49445236e2e.png">
