### ISSUE TITLE
Problem getting responders

### ISSUE THREAD

**Issue by curiousier-george** [kevinzg/facebook-scraper#578]
This program snippet

```
from facebook_scraper import get_posts
from pprint import pprint
import sys

cookie_file = 'facebook_cookies.txt'

def get_post_reactors(post_id):

    post = next(get_posts(post_urls=[post_id], cookies=cookie_file,
                          options={'allow_extra_requests': False, 'reactors': True, 'HQ_images': False}))

    return post.get('reactors', None)

post_ids = sys.argv[1 :]

for post_id in post_ids:
    print(post_id)
    pprint(get_post_reactors(post_id))``
```

usually works to get the reactors to a given post like this
`python reactors.py 10224355198279890`
But on some posts it doesn't return the reactors. For example, this
`python reactors.py 10224039043141034`
and this
`python reactors.py 10217951702498185`
both return none of the reactors for me, and I have not been able to figure out why.

Do you have any idea what the problem might be?

**Comment by neon-ninja** [comment]
Looks like a problem specific to image posts. This commit should fix it - https://github.com/kevinzg/facebook-scraper/commit/d3b16c54c1c3963ebb277e8e52a89837ef65a222

**Comment by curiousier-george** [comment]
Thank you, that fixes all of the problems I'd encountered!

I do have another bug report now, though, this time with
`post_id = 10224047792519763`. (It's a Facebook 'fundraiser'.)

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/f1645b23612a179b7b257e6259bc25e33605c014 should fix extraction for this kind of post

**Comment by curiousier-george** [comment]
Hmm, I'm still not retrieving any reactors for that post after installing the fix with
`pip install git+https://github.com/kevinzg/facebook-scraper.git`.
Do you know of something I may be doing wrong?

**Comment by neon-ninja** [comment]
Ah, I though you were complaining post extraction wasn't working for these kinds of posts, that's what that commit fixes. I didn't test reactor extraction with that kind of post

**Comment by curiousier-george** [comment]
I hope my bug reports don't actually sound like complaining. 😊 facebook-scraper is a great project and very well done. Thank you! I appreciate it a lot.

**Comment by neon-ninja** [comment]
The code:

```python
pprint(
    next(
        get_posts(
            post_urls=["10224047792519763"],
            cookies="cookies.json",
            options={'allow_extra_requests': False, "reactors": True},
        )
    )
)
```
outputs:
```python
{'available': True,
 'comments': 0,
 'comments_full': None,
 'factcheck': None,
 'fetched_time': datetime.datetime(2021, 12, 7, 19, 42, 3, 789839),
 'header': "Regan Wilson Takac donated to Karen Caswell Sapia's birthday "
           'fundraiser for Planned Parenthood.',
 'image': None,
 'image_id': None,
 'image_ids': [],
 'image_lowquality': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t39.30808-6/p320x320/241324318_4958663060816365_5914801301839414643_n.png?_nc_cat=107&ccb=1-5&_nc_sid=870f81&efg=eyJpIjoidCJ9&_nc_ohc=fwEzDccwXDUAX8y6Bl4&tn=OSRvVCTXmWI5cMmn&_nc_ht=scontent.fakl8-1.fna&oh=676ac77b5d91f9b714731ffb2839b2fb&oe=61B4DA13',
 'images': None,
 'images_description': None,
 'images_lowquality': ['https://scontent.fakl8-1.fna.fbcdn.net/v/t39.30808-6/p320x320/241324318_4958663060816365_5914801301839414643_n.png?_nc_cat=107&ccb=1-5&_nc_sid=870f81&efg=eyJpIjoidCJ9&_nc_ohc=fwEzDccwXDUAX8y6Bl4&tn=OSRvVCTXmWI5cMmn&_nc_ht=scontent.fakl8-1.fna&oh=676ac77b5d91f9b714731ffb2839b2fb&oe=61B4DA13'],
 'images_lowquality_description': [None],
 'is_live': False,
 'likes': 3,
 'link': None,
 'links': [],
 'original_request_url': '10224047792519763',
 'page_id': None,
 'post_id': '10224047792519763',
 'post_text': '',
 'post_url': 'https://facebook.com/story.php?story_fbid=10224047792519763&id=1002863265',
 'reaction_count': None,
 'reactions': {'like': 3},
 'reactors': [{'link': 'https://facebook.com/iambeulah?fref=pb',
               'name': 'Nancy Hamilton',
               'type': 'like'},
              {'link': 'https://facebook.com/vicka.pevzner?fref=pb',
               'name': 'Vicka Kharitonova Pevzner',
               'type': 'like'},
              {'link': 'https://facebook.com/ehbraun?fref=pb',
               'name': 'Ellen H. Braun',
               'type': 'like'}],
 'shared_post_id': None,
 'shared_post_url': None,
 'shared_text': None,
 'shared_time': None,
 'shared_user_id': None,
 'shared_username': None,
 'sharers': None,
 'shares': 0,
 'text': '',
 'time': datetime.datetime(2021, 11, 26, 1, 29),
 'timestamp': None,
 'user_id': None,
 'user_url': 'https://facebook.com/regan.takac?refid=52&__tn__=C-R',
 'username': 'Regan Wilson Takac',
 'video': None,
 'video_duration_seconds': None,
 'video_height': None,
 'video_id': None,
 'video_quality': None,
 'video_size_MB': None,
 'video_thumbnail': None,
 'video_watches': None,
 'video_width': None,
 'w3_fb_url': 'https://www.facebook.com/story.php?story_fbid=10224047792519763&id=1002863265',
 'was_live': False,
 'with': [{'link': '/kcsapia?refid=52&__tn__=C-R',
           'name': 'Karen Caswell Sapia'}]}
```
for me - all 3 reactors appear to have been correctly extracted. Do you not get the same?

**Comment by curiousier-george** [comment]
No, I don't. I only get
```
{'original_request_url': '10224047792519763',
 'post_url': 'https://m.facebook.com/10224047792519763'}
```
Would that mean I don't actually have the latest version that includes the fix?

**Comment by neon-ninja** [comment]
Sounds like it. Try a `pip uninstall facebook-scraper` before you `pip install`

**Comment by curiousier-george** [comment]
That worked! Thank you.
